#!/bin/bash
#This file consist's of the main script to run the tool

# for adding the given template
if [[ $1 == "--add" ]]
then
    if [[ -d "$HOME/.config/Autotemp/templates" ]]
    then
        touch "$HOME/.config/Autotemp/templates/$2.txt"
        echo  "Enter the contents of template"
        cat > "$HOME/.config/Autotemp/templates/$2.txt"
        printf "\n"
        echo "=================================================="
        echo "Template $2 succesfully created the contents are:"
        echo "=================================================="
        printf "\n"
        cat "$HOME/.config/Autotemp/templates/$2.txt"
    fi

# list out all existing templates
elif [[ $1 == "-l" ]]
then
    ls "$HOME/.config/Autotemp/templates/"

# printf all the content in the given template
elif [[ $1 == "-pf" ]]
then
    more "$HOME/.config/Autotemp/templates/$2.txt"

# gives specific path to where the template is to be written over (file must already exist)
elif [[ $1 == "-p" ]]
then 
    cat "$HOME/.config/Autotemp/templates/$2.txt" >> "$3"

# for editing the template file
elif [[ $1 == "-e" ]]
then
    echo "Opening $2 file in vim, do edit as required"
    vim "$HOME/.config/Autotemp/templates/$2.txt"

# for removing a template file
elif [[ $1 == "-r" ]]
then    
    echo "Removing File $2 from the template store"
    rm "$HOME/.config/Autotemp/templates/$2.txt"

# help function to tell more about the command usage
elif [[ $1 == "--help" || $1 == "--h" ]] 
then 
    more "$HOME/.config/Autotemp/help.txt"
else
    if [[ $# -eq 1 ]]
    then
        echo "invalid input use autotemp --help for help"
    else
        if [[ -f "$HOME/.config/Autotemp/templates/$1.txt" ]]
        then

        cat "$HOME/.config/Autotemp/templates/$1.txt" | tee -a "${@:2}" > "/dev/null" 
            
        else
            echo "provided template doesnot exist create one using --add "
        fi
    fi
fi
